# Generated by Django 4.1.6 on 2023-02-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
